geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admin-staff/', include('admins.urls', namespace='admin_staff')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import OrderListView, OrderCreateView, \
    OrderDeleteView, OrderDetailView, OrderUpdateView, order_forming_complete

app_name = 'orders'

urlpatterns = [
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('', OrderListView.as_view(), name='order_list'),
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='order_delete'),
    path('detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
]

users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout, verify

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('verify/<str:email>/<str:activate_key>/', verify, name='verify'),

]

orders/models.py
from django.db import models
from django.conf import settings
from products.models import Product


class Order(models.Model):
    FORMING = 1
    SENT_TO_PROCEED = 2
    PAID = 3
    PROCEEDED = 4
    READY = 5
    CANCEL = 6

    ORDER_STATUSES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='время создания', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='время изменения', auto_now=True)
    status = models.PositiveIntegerField(
        choices=ORDER_STATUSES, verbose_name='Статус', default=FORMING)
    is_active = models.BooleanField(verbose_name='Активен', default=True)

    def __str__(self):
        return f'Текущий заказ: {self.pk}'

    @property
    def get_total_cost(self):
        items = self.items.select_related()
        return sum(list(map(lambda x: x.cost, items)))

    @property
    def get_total_quantity(self):
        items = self.items.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def delete(self, using=None, keep_parents=False):
        for item in self.items.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, verbose_name='Заказ', related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, verbose_name='Продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)

    @property
    def cost(self):
        return self.product.price * self.quantity

orders/forms.py
from django import forms
from orders.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

orders/views.py
from django.forms import inlineformset_factory
from django.http import  HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from baskets.models import Basket
from orders.models import Order, OrderItem
from orders.forms import OrderItemForm, OrderForm


class OrderListView(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderDetailView(DetailView):
    model = Order


class OrderCreateView(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:order_list')


class OrderDeleteView(DeleteView):
    pass


class OrderUpdateView(UpdateView):
    pass


def order_forming_complete():
    pass

orders/templates/orders/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

</head>

<body>

</body>

</html>

orders/templates/orders/order_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

orders/templates/orders/order_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

orders/templates/orders/order_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

orders/templates/orders/order_list.html
{% extends 'orders/base.html' %}
{% load static %}

{% block content %}
    <div class="h2 text-center head">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.first_name|title }}
        {% else %}
            Пользователь
        {% endif %}
    </div>
    <table class="table orders_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a href="{% url 'orders:order_read' item.pk %}">
                            посмотреть
                        </a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'orders:order_update' item.pk %}">
                                редактировать
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'orders:order_delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'main' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'orders:order_create' %}">
            новый
        </a>
    </button>
{% endblock %}